### PR TITLE
ReferringTo Predicate to filter by foreign id referring to a row in another table #46

### PR DESCRIPTION
**Pull request by lemonboston**

### CODE REVIEW

**Comment by dmfs** [comment]
Please rebase on master, #45 has already been merged.

**Comment by lemonboston** [comment]
Rebased on master.

**Comment by lemonboston** [comment]
I have problem using it since the id is evaluated in the constructor eagerly supposedly before the `VirtualRowSnapshot` can be resolved..     so we may need lazy evaluation for that here. (Not totally sure)

**Comment by dmfs** [comment]
Right. This also requires a bit more work to make it work with `VirtualRowSnapshots` because we don't have support for "selection back references" yet.

**Comment by lemonboston** [comment]
Rebased, updated to use lazy evaluation.
I don't know if there is a potential issue with this usage, but its copy (RefersTo) is working now in OpenTasks. Can we use this?
Ready for review.

**Comment by lemonboston** [comment]
This is basically the same as this one already in use in `CalendarScoped`:
```
    private Predicate calendarScoped(@NonNull Predicate predicate)
    {
        return new AllOf(predicate, new EqArg(CalendarContract.Events.CALENDAR_ID,
                mCalendarRow.values().charData(CalendarContract.Calendars._ID).value("-1")));
    }
```
(This was the basic motivation to create it)

So I would assume it should be okay, right?

**Comment by dmfs** [comment]
Well, now that I see this code in isolation I can see that it's clearly wrong and only works under certain circumstances. The `insertOperation` code is ok, but update or delete will fail if you use this for a table which has just been created. And it doesn't matter whether the table has already been committed or not. If `mCalendarRow` is a `VirtualRowSnapshot` this will always fail.

**Comment by lemonboston** [comment]
Does that also explain why the `updateDue()` test fails in OpenTasks currently?
This is the stacktrace there when asserting after a Put update operation:
```
        java.lang.IllegalArgumentException: uri must not be null
            at android.content.ContentProviderOperation$Builder.<init>(ContentProviderOperation.java:502)
            at android.content.ContentProviderOperation$Builder.<init>(ContentProviderOperation.java)
            at android.content.ContentProviderOperation.newAssertQuery(ContentProviderOperation.java:200)
            at org.dmfs.android.contentpal.references.RowUriReference.assertOperationBuilder(RowUriReference.java:66)
            at org.dmfs.android.contentpal.operations.Assert.contentOperationBuilder(Assert.java:62)
            at org.dmfs.android.contentpal.transactions.BaseTransaction.with(BaseTransaction.java:105)
```

**Comment by dmfs** [comment]
I don't think so. I'll check that.

**Comment by dmfs** [comment]
I think the problem is that all types of operations end up in the ResultTransactionContext, but it should only consider operations which resulted in a Uri. I'll open an issue.

**Comment by dmfs** [comment]
I'm not going to merge this class like this. It's just not reliable enough. For the time being you can keep it in the OpenTasks provider test module if it works in that scenario, but it shouldn't be in here, especially since we already have alternative approaches at hand (#51 and #52).

**Pull request closed without merging**
