### PR TITLE
Change RowDataSnapshot interface for more convenient usage. #136

### PR DESCRIPTION
**Pull request by lemonboston**
Note that it waits for jems release (uses jjitpack now).

### CODE REVIEW

**Comment by lemonboston** [comment]
I have problems building it locally now, not sure why, this is my last error I get:
```
java.lang.RuntimeException: java.lang.RuntimeException: com.android.builder.dexing.DexArchiveMergerException: Unable to merge dex
```
Maybe it reached the dex limit, but let's just wait for new jems and check then.

So I missed some places that needs to updated, I've updated them now.

**Comment by dmfs** [comment]
You're probably importing the same library twice from two different sources. E.g. if a dependency depends on a `jems` version from maven and you're importing it from jitpack. For Gradle these are two different dependencies providing the same classes. You can see the actual reason when you build on the command line with `--stacktrace`.

**Comment by lemonboston** [comment]
Reverted to use jems 1.14 from maven and made local, deprecated copies of the yet to be released classes. Builds now successfully.

Squash-rebased, ready for review.

**Comment by dmfs** [comment]
lets wait for jems 1.15 before merging this

**Comment by lemonboston** [comment]
Updated to jems 1.15, ready for check and merge.

**Review by dmfs — APPROVED** [review]

**Pull request merged**
