### PR TITLE
Field Single for accessing a field with reflection. #102

### PR DESCRIPTION
**Pull request by lemonboston**
Note that this is based on the branch of #101-#104 because jems has been updated there already making `Single` available.
I'll rebase when that one is merged.

### CODE REVIEW

**Review by dmfs — CHANGES_REQUESTED** [review]
I know `Field` is rather trivial, but I want a unit test. That shouldn't take much time. Other than that it looks good.

**Comment by lemonboston** [comment]
I've added the unit test.

**Comment by dmfs** [comment]
#104 has been merged, please rebase

**Comment by lemonboston** [comment]
Rebased.

**Review by dmfs — APPROVED** [review]

**Pull request merged**
