### PR TITLE
Move predicate test util classes from contentpal to contentpal-testin…

### PR DESCRIPTION
**Pull request by lemonboston**
…g. #99

### CODE REVIEW

**Comment by dmfs** [comment]
Why did the test coverage drop by 8%? That's strange.

**Comment by lemonboston** [comment]
It's not clear for me from the report. 8% doesn't seem correct even if coverage dropped because of the duplicate `ValueArgument`.

**Review by dmfs — APPROVED** [review]
Looks good to me. On my Machine I still get 44% coverage.

**Comment by dmfs** [comment]
let's see what it says for master after the merge.

**Pull request merged**
