### PR TITLE
Assert operations for checking rows with foreign keys in tests. #70

### PR DESCRIPTION
**Pull request by lemonboston**

### CODE REVIEW

**Review by dmfs — COMMENTED** [review]
Let's wait with this until either #51, #52 or any other solution to this problem has been accepted and merged. Also I'm wondering if we can't compose `PostOperationRelatedBulkAssert` from a regular `Assert` or `BulkAssert`

**Comment by dmfs** [comment]
for now, please rebase on master and delete the `issues/54-testing-mod-n-contentmatcher` branch

**Comment by lemonboston** [comment]
Oh, it got closed automatically because of the deleted branch, I should have changed base branch of the PR before. I am going to open a new one.

**Comment by lemonboston** [comment]
Oh, I could still change base here and reopen.

**Comment by dmfs** [comment]
@lemonboston please rebase on master

**Comment by lemonboston** [comment]
These `PostOperation*` classes here are outdated now with the new support for `ReferringTo(Predicate)` so I close this an open a new pull request.

**Pull request closed without merging**
