### PR TITLE
Add EagerOperationsQueue. Implements #30

### PR DESCRIPTION
**Pull request by dmfs**
This also renames BasicOperationsQueue to LazyOperationsQueue to make the difference more apparent.

### CODE REVIEW

**Review by lemonboston — CHANGES_REQUESTED** [review]
The code looks good, but this `EagerOperationsQueue` isn't really an `OperationsQueue` any more for me. I mean that the method name `enqueue` doesn't fit well any more, it's more like `execute` or `commit`, the javadoc of the method on the interface refers to the first implementation. So it kind of violates the contract, also shown in `flush()` which does nothing now.
Not sure what would be the best way though, have a narrower base interface and extend that with flush() or have a different one, or figure something else out.

I think probably to have a separate interface. Because if we think about client usage, it wouldn't know if it has Eager or Lazy queue, so it would always call flush().
And in case there is a base interface with enqueue(), then the extended one could be passed around as the base type as well, meaning client code may incorrectly assume it will flush() on its own. So I think we need a distinct interface here for the eager implementation with a single method.

**Comment by dmfs** [comment]
Hmm... let me think about your objection. To be honest, I don't really like the `OperationsQueue` interface, because it's not designed for immutability. But so far I couldn't come up with a better solution, especially when having the use cases in mind.

Having a narrower or different interface won't make the implementations interchangeable. At present I'm not sure if that matters or if the use cases are entirely disjunct and it doesn't matter.

**Comment by lemonboston** [comment]
What if we just have a convenience extended interface for the eager use-cases?

```
interface ConvenientOperationsQueue extends OperationsQueue
{
        void execute(OperationsBatch batch);
        void execute(Operation... operations);
}
```
So then we just need an adapter that calls `enqueue` and `flush()`. If the aim was also to have better performance with the `Eager` queue, then it doesn't fulfills that of course, but otherwise it can help easier usage when eager calls are needed.

**Comment by lemonboston** [comment]
This proposed interface above could also just be added to test support, to help write the tests more concisely. Not sure what's the best name for it.

But the test could change from:
```
        OperationsQueue queue = new BasicOperationsQueue(mClient);

        queue.enqueue(new MultiBatch(
                new Put<>(taskList, new NameData("list1")),
                new Put<>(task, new TitleData("task1"))
        ));
        queue.flush();
```
to
```
        CommitingQueue queue = new CommitingQueue(new BasicOperationsQueue(mCleint);
         // could have shortcut ctor of course
        
        queue.commit(new Put<>(taskList, new NameData("list1")),
                new Put<>(task, new TitleData("task1")));
```

Not that important altogether though.

**Comment by dmfs** [comment]
Actually the `OperationsQueue` thing is more like a convenience thing. If you just want to commit a few Batches you could do this instead:
```java
TransactionContext context = new BaseTransaction()
    .with(
        new Joined(
            new Put<>(taskList, new NameData("list1")),
            new Put<>(task, new TitleData("task1"))
        )
    )
    .commit(mClient);
```
you just have to make sure to pass the resulting context to the next `Transaction` like this:
```java
TransactionContext newContext = new BaseTransaction(context)
    .with( … )
    .commit(mClient);
```
otherwise references to rows committed in the earlier transaction won't work.

And that's essentially what `BasicOperationsQueue` does for you. It maintains the `TransactionContext` (and automatically commits transactions when they grow too large).

So the question is, can we find a better way to handle this?

**Comment by lemonboston** [comment]
I see, this can be done with purely `BaseTransaction` as well. 
I am not sure how much else this can be simplified, and not sure what use-cases you have in mind. Do you think about production code use-cases as well or just the tests?

> Sometimes the use case doesn't justify the boilerplate code required to create and close a ContentProviderClient in order to use a BasicOperationsQueue
> What we need is another simple OperationsQueue which just executes every OperationsBatch instantly using ContentResolver.applyBatch(…).

So something like this?:
```
new Something(authority, batch).commit(context)
or
new Something(authority).commit(context, batch)
```
So instead of having the `client` as 'execution parameter', use the `context`.

I am not sure we could use this in the tests since we usually need to keep the `TransactionContext` for the assertions later.

> This is also useful when using assert operations, because the lazyness of BasicOperationsQueue makes it unsuitable for assert operations. You wouldn't know which OperationsBatch actually caused an error and some operations might have been executed, while everything after the erroneous batch would be "lost".

I am not sure I understand this part. Did you mean tests here or production code? In tests, the `Assert` operation exceptions work okay, I think.

**Comment by dmfs** [comment]
The use cases I have in mind are not so much separated into test vs. production code. It's more like this

* execution of a single batch without the need to preserve the `TransactionContext`, the typical use case of this pattern is a contact, event or task editor app. This can be perfectly handled with a `BaseTransaction` alone.
* execution of a few batches with preserved `TransactionContext`s, possibly with a query in between, test code is a typical use case for this. A `BaseTransaction` alone could handle this but might be inconvenient.
* execution of many (potential large and often related) transactions like it might occur during synchronization. A `BaseTransaction` alone can't handle this case.

The last case clearly requires preservation of the `TransactionContext` and it most likely requires sort of a mutable queue which receives batches for (if possible, lazy) execution.

The second and third use case might also require to give access to the transaction context in order to run queries with predicates with virtual rows.

>  In tests, the Assert operation exceptions work okay, I think.
That's true because in tests, you don't really care which part fails. The goal is to pass the test. When you execute a bunch of compare & swap operations (e.g. during synchronization) this might not be true anymore. Consider the following sync flow:

1. client reads status (e.g. version number) local contacts 
2. client reads changes from server
3. client updates local contacts asserting the version number it has read earlier, to ensure it operates on up-to-date data. 

Now if another app modified one contact between step 1 and 3, the version number of that contact would be increased and the assertion in step 3 would fail for that contact. But since a bunch of contacts have been updated in the transaction you don't know which one failed. More over, the changes prior to the assert operation may or may not have been committed to the database (depending on where yield points have been set and whether they have actually been taken as such).

Depending on the overall sync mechanism, this might not be a problem, but it must be considered when working with this.

**Comment by dmfs** [comment]
Long story short, a separate interface for use case 2 seems like the way to. I'm just not sure how it would look like and how to maintain the `TransactionContext`.

**Comment by dmfs** [comment]
Closing this for now, we definitely need a better solution.

**Pull request closed without merging**
