### PR TITLE
Add support for JaCoCo and Codecov.io. Implements #82

### PR DESCRIPTION
**Pull request by dmfs**
This commit does essentially two things:

* Integrate jacoco-android-gradle-plugin to add a task to create JaCoCo reports
* update .travis.yml to create JaCoCo reports and upload them to codecov.io

The reports can be seen at https://codecov.io/gh/dmfs/ContentPal
I'm not sure if codecov.io posts any reports to the PR like it did in the carrot project. That might require additional configuration. We'll see.

### CODE REVIEW

**Comment by dmfs** [comment]
It should be safe to ignore the failed codecov check. It's probably just because it can't tell if the coverage improved or declined because there is no report for master yet.

Before merging this needs to be rebased on master and the test project's build.gradle needs to be updated.

**Comment by dmfs** [comment]
Rebased and updated build files. @lemonboston Ready for review.

**Review by lemonboston — APPROVED** [review]
I suppose it's not worth spending time on my side in getting to know and experimenting with jacoco configurations, so I approve it without that. It builds for me, and I see the report files generated.

So I guess it can be merged after rebased on master and the new test module gradle file updated, as you mentioned.

**Comment by lemonboston** [comment]
Looks good after the rebase and update, too.

**Pull request merged**
