### PR TITLE
Move dependency lists to dependencies.gradle file. #151

### PR DESCRIPTION
**Pull request by lemonboston**
Small note: Gradle complained with some error about that 'clean' task in the root build.gradle file, not sure why, but I just removed it.

Also updated gradle to 4.3 while I was troubleshooting, it is probably not needed but it doesn't hurt either.

### CODE REVIEW

**Comment by dmfs** [comment]
I can't really get used to this. It looks wrong to merge module specific settings in a single file. Sharing common code/settings between modules is useful and makes a lot of sense. Module specific stuff should stay inside that module.

**Comment by lemonboston** [comment]
I know it feels wrong generally because of moving out module specific things to a common place, but I couldn't imagine any real, actual problem that it could realize into. So the easier usage (not having to look for the gradle file, and no chance of mistaking it) and easier maintenance of dependency relations of the modules (can see them next to each other) won for me.
But it's also not that important, so I've moved them back to the module's gradle files.

Ready for check again.

**Comment by dmfs** [comment]
did you push your changes? Also, please rebase.

**Comment by lemonboston** [comment]
I did. Here: https://github.com/dmfs/opentasks/pull/653 :)
I thought this was OpenTasks...   I will get back to this and update here, too.

**Comment by lemonboston** [comment]
Since this pull request was about moving the declared dependencies and we are not going to do that, I close it.

**Pull request closed without merging**
